---
redisOperator:
  name: redis-operator
  imageName: quay.io/opstree/redis-operator
  imageTag: v0.8.0
  imagePullPolicy: Always

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 500Mi

replicas: 1

serviceAccountName: redis-operator

priorityClassName: ""
nodeSelector: {}
tolerateAllTaints: false
tolerations: []
affinity: {}
